version: '2'

services:
  server1:
    build: server/

  server2:
    build: server/

  server3:
    build: server/

  server4:
    build: server/

  lb:
    build: lb/
    ports: 
      - "8000:8000"

  lb-exporter:
    image: quay.io/prometheus/haproxy-exporter
    command: --haproxy.scrape-uri="http://admin:admin@lb:8001/haproxy?stats;csv"

  prometheus:
    build: prometheus/
    ports:
      - "9090:9090"

  # load:
  #  build: load/    
    
